import Foundation

struct DisplayEntry: Codable, Equatable {
    let name: String
    let vendor: UInt32
    let model: UInt32
}

struct FlexibleDisplay: Codable, Equatable {
    let name: String
    let vendor: UInt32
    let model: UInt32
    let position: Position
    let relative_to: String       // "builtin" or a display name
    let align: Alignment
    let offset: Int?              // pixels from the align anchor, default 0
    let rotation: Int?            // 0, 90, 270 — informational for now

    enum Position: String, Codable {
        case above, below, left, right
    }

    enum Alignment: String, Codable {
        case top, center, bottom    // for left/right positioning
        case left_edge = "left"     // for above/below positioning
        case right_edge = "right"   // for above/below positioning
        // "center" works for both axes
    }

    var effectiveOffset: Int { offset ?? 0 }
}

struct Config: Codable {
    var stacked: [DisplayEntry]
    var ignored: [DisplayEntry]
    var flexible: [FlexibleDisplay]

    static let configDir = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent(".config/display-align")
    static let configFile = configDir.appendingPathComponent("config.json")

    static func load() -> Config {
        guard FileManager.default.fileExists(atPath: configFile.path),
              let data = try? Data(contentsOf: configFile),
              var config = try? JSONDecoder().decode(Config.self, from: data)
        else {
            // First run: seed with the known Dell in stacked
            let initial = Config(
                stacked: [DisplayEntry(name: "DELL P3424WEB", vendor: 4268, model: 17092)],
                ignored: [],
                flexible: []
            )
            initial.save()
            return initial
        }
        if config.migrateAutoGeneratedNames() {
            config.save()
        }
        return config
    }

    /// Refresh entries whose `name` is the legacy auto-generated
    /// `Vendor(<n>) [model:<m>]` placeholder. User-customized names
    /// (e.g. `"DELL P3424WEB"`) don't match the pattern and stay put.
    /// Also rewrites any `flexible.relative_to` reference that points at
    /// a renamed entry, so anchors don't break.
    /// Returns `true` if any entry was rewritten — caller should `save()`.
    mutating func migrateAutoGeneratedNames() -> Bool {
        func regenerated(_ name: String, vendor: UInt32, model: UInt32) -> String? {
            guard name.range(of: #"^Vendor\(\d+\) \[model:\d+\]$"#, options: .regularExpression) != nil
            else { return nil }
            let updated = "\(Vendor.name(for: vendor)) [model:\(model)]"
            return updated == name ? nil : updated
        }

        // Pass 1: collect old-name → new-name across every list, so
        // pass 2 can update both names *and* relative_to references.
        var renames: [String: String] = [:]
        for e in stacked + ignored {
            if let newName = regenerated(e.name, vendor: e.vendor, model: e.model) {
                renames[e.name] = newName
            }
        }
        for f in flexible {
            if let newName = regenerated(f.name, vendor: f.vendor, model: f.model) {
                renames[f.name] = newName
            }
        }
        guard !renames.isEmpty else { return false }

        stacked = stacked.map { e in
            guard let newName = renames[e.name] else { return e }
            return DisplayEntry(name: newName, vendor: e.vendor, model: e.model)
        }
        ignored = ignored.map { e in
            guard let newName = renames[e.name] else { return e }
            return DisplayEntry(name: newName, vendor: e.vendor, model: e.model)
        }
        flexible = flexible.map { f in
            let newName = renames[f.name] ?? f.name
            let newRelative = renames[f.relative_to] ?? f.relative_to
            guard newName != f.name || newRelative != f.relative_to else { return f }
            return FlexibleDisplay(
                name: newName, vendor: f.vendor, model: f.model,
                position: f.position, relative_to: newRelative,
                align: f.align, offset: f.offset, rotation: f.rotation
            )
        }
        return true
    }

    func save() {
        do {
            try FileManager.default.createDirectory(at: Self.configDir, withIntermediateDirectories: true)
            let encoder = JSONEncoder()
            encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
            let data = try encoder.encode(self)
            try data.write(to: Self.configFile, options: .atomic)
        } catch {
            print("Failed to save config: \(error)")
        }
    }

    func isStacked(vendor: UInt32, model: UInt32) -> Bool {
        stacked.contains { $0.vendor == vendor && $0.model == model }
    }

    func isIgnored(vendor: UInt32, model: UInt32) -> Bool {
        ignored.contains { $0.vendor == vendor && $0.model == model }
    }

    func isFlexible(vendor: UInt32, model: UInt32) -> Bool {
        flexible.contains { $0.vendor == vendor && $0.model == model }
    }

    func isKnown(vendor: UInt32, model: UInt32) -> Bool {
        isStacked(vendor: vendor, model: model)
            || isIgnored(vendor: vendor, model: model)
            || isFlexible(vendor: vendor, model: model)
    }

    mutating func addStacked(_ entry: DisplayEntry) {
        guard !isKnown(vendor: entry.vendor, model: entry.model) else { return }
        stacked.append(entry)
        save()
    }

    mutating func addIgnored(_ entry: DisplayEntry) {
        guard !isKnown(vendor: entry.vendor, model: entry.model) else { return }
        ignored.append(entry)
        save()
    }
}
